# Generated by Django 3.2 on 2023-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230306_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_degrees',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
